package entities;

// Generated Jan 7, 2017 11:34:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.sun.xml.internal.bind.v2.runtime.unmarshaller.XsiNilLoader.Array;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "Users", catalog = "tpjad", uniqueConstraints = @UniqueConstraint(columnNames = "fullName"))
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String fullName;
	private String password;
	private String email;
	private Set<Tests> testses = new HashSet<Tests>(0);
	private Set<Results> resultses = new HashSet<Results>(0);

	public Users() {
	}

	public Users(int id, String fullName, String password, String email) {
		this.id = id;
		this.fullName = fullName;
		this.password = password;
		this.email = email;
	}

	public Users(int id, String fullName, String password, String email,
			Set<Tests> testses, Set<Results> resultses) {
		this.id = id;
		this.fullName = fullName;
		this.password = password;
		this.email = email;
		this.testses = testses;
		this.resultses = resultses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "fullName", unique = true, nullable = false)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Tests> getTestses() {
		return this.testses;
	}

	public void setTestses(Set<Tests> testses) {
		this.testses = testses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Results> getResultses() {
		return this.resultses;
	}

	public void setResultses(Set<Results> resultses) {
		this.resultses = resultses;
	}

	public String toString() {
		return "{\"id\":" + id + ", \"fullName\":\"" + fullName
				+ "\", \"email\":\"" + email + "\"}";
	}

}
